name: medminder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- FIREBASE ---
  firebase_core: ^3.1.1
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  firebase_app_check: ^0.3.0+1

  # --- NOTIFICATIONS & TIME ---
  flutter_local_notifications: ^17.2.1+2
  flutter_timezone: ^5.0.0

  # --- UTILITY PACKAGES ---
  flutter_slidable: ^3.1.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  file_picker: ^8.0.6
  url_launcher: ^6.3.0
  provider: ^6.1.2
  path: ^1.9.0
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
